
# This file is automatically generated, you probably don't want to edit this

contingencytableOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contingencytableOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            rowVar = NULL,
            colVar = NULL,
            generate = NULL, ...) {

            super$initialize(
                package="ContingencyTable",
                name="contingencytable",
                requiresData=TRUE,
                ...)

            private$..rowVar <- jmvcore::OptionVariable$new(
                "rowVar",
                rowVar,
                required=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..colVar <- jmvcore::OptionVariable$new(
                "colVar",
                colVar,
                required=TRUE,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..generate <- jmvcore::OptionAction$new(
                "generate",
                generate)

            self$.addOption(private$..rowVar)
            self$.addOption(private$..colVar)
            self$.addOption(private$..generate)
        }),
    active = list(
        rowVar = function() private$..rowVar$value,
        colVar = function() private$..colVar$value,
        generate = function() private$..generate$value),
    private = list(
        ..rowVar = NA,
        ..colVar = NA,
        ..generate = NA)
)

contingencytableResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contingencytableResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Contingency Table")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title=""))}))

contingencytableBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "contingencytableBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ContingencyTable",
                name = "contingencytable",
                version = c(1,0,0),
                options = options,
                results = contingencytableResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Contingency Table
#'
#' 
#' @param data .
#' @param rowVar .
#' @param colVar .
#' @param generate .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
contingencytable <- function(
    data,
    rowVar,
    colVar,
    generate) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("contingencytable requires jmvcore to be installed (restart may be required)")

    if ( ! missing(rowVar)) rowVar <- jmvcore::resolveQuo(jmvcore::enquo(rowVar))
    if ( ! missing(colVar)) colVar <- jmvcore::resolveQuo(jmvcore::enquo(colVar))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(rowVar), rowVar, NULL),
            `if`( ! missing(colVar), colVar, NULL))

    for (v in rowVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in colVar) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- contingencytableOptions$new(
        rowVar = rowVar,
        colVar = colVar,
        generate = generate)

    analysis <- contingencytableClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

